### ISSUE TITLE
Alien Syndrome S16B screen tearing

### ISSUE THREAD

**Issue by JanGunheD** [JTFPGA/jts16#80]
Alien Syndrome on S16b shows screen tearing in the upper part of the screen. This did not happen in previous versions. Any post filtering in the core solves the issue, like CRT or integer scaling.

**Comment by jotego** [comment]
Hello, 

Look at this [thread](https://github.com/jotego/jtcores/issues/313). Please check the core version you are using. The latest one is 8533440.

I will close the issue here and also hide this repository as this is an old copy of the jts16 core, which is now hosted in the jtcores repository. Please comment in the other thread if necessary.
